### ISSUE TITLE
how to use kubectl logs/exec

### ISSUE THREAD

**Issue by zoux86** [virtual-kubelet/tensile-kube#83]
i built two k8s cluster, cluster-high  and cluster-low, cluster-low is the virtual-kubelet, cluster-high is the master cluster.

And i had a running pod in virtual-kubelet .
but when i use kubectl logs , it always return error, so i I  wonder how to deploy virtual-kubelet to user kubectl logs.

#### details

（1）build Binary： virtual-node

```
# git clone https://github.com/virtual-kubelet/tensile-kube.git 
# make provider
```

（2）run virtual-node

i run virtual-node in cluster-high(master cluster) with these commands。

```
set env
# export APISERVER_CERT_LOCATION=/root/cluster-low/admin.pem 
# export APISERVER_CA_CERT_LOCATION=/root/cluster-low/ca.pem
# export APISERVER_KEY_LOCATION=/root/cluster-low/admin-key.pem 
# export KUBELET_PORT=10250


run the command
# ./bin/virtual-node --kubeconfig /root/.kube/config --client-kubeconfig /root/cluster-low/kube-config --enable-controllers "" --log-level debug
```

 By the way:

```
# cat /root/cluster-low/kube-config
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/cluster-low/ca.pem
    server: https://xxx:10285
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate: /root/cluster-low/admin.pem
    client-key: /root/cluster-low/admin-key.pem
```

in cluster-low, kubelet flags is here

```
/usr/local/bin/kubelet --address=xxx --port=10250
```

（3）run pod, and test logs

when i run a pod in virtual-kubelet，i found it return this error:  **tls: bad certificate**

```
in cluster-high
# kubectl get pod -n test -o wide
NAME        READY   STATUS    RESTARTS   AGE     IP           NODE              NOMINATED NODE   READINESS GATES
test-pod2   1/1     Running   0          4h14m   7.34.19.16   virtual-kubelet   <none>           <none>

# kubectl logs test-pod2  -n test
Error from server: Get "https://:10250/containerLogs/test/test-pod2/busbox": remote error: tls: bad certificate
```

virtual-kubelet had this logs:
2022/05/31 14:36:44 http: TLS handshake error from 127.0.0.1:44578: tls: client didn't provide a certificate

<br>

#### questions

so i want to ask why i cannot use kubectl logs?

（1）is the env: KUBELET_PORT，APISERVER_CERT_LOCATION，APISERVER_CA_CERT_LOCATION，APISERVER_KEY_LOCATION is not set correctly？

（2）i should not run virtual-node in cluster-high(i run it in master1)?  i had try to  run virtual-node in cluster-low, it didn't sucess.
